main:
  - name: home
    pageRef: /
    weight: 10
  - name: about
    pageRef: /about
    weight: 20
  - name: consulting
    pageRef: /consulting
    weight: 30
  - name: projects
    pageRef: /consulting/projects
    weight: 40
  - name: denktmit
    pageRef: /denktmit
    weight: 50
  - name: blog
    pageRef: /blog
    weight: 60
  - name: contact
    pageRef: /contact
    weight: 70
#    - name: Tags
#      pageRef: /tags
#      weight: 30
