name: Deploy to prod

on:
  push:
    branches:
      - main
      - two-column-poc

  workflow_dispatch:

jobs:
  build:
    name: Build Hugo site
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.137.1
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb          

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build with Hugo
        working-directory: ./hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify          

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-artifact
          path: './hugo/public'

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release-artifact
          path: './public'

      - name: Transfer files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ vars.SERVER }}
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          protocol: ${{ vars.PROTOCOL }}
          port: ${{ vars.PORT }}
          local-dir: './public/'
